### ISSUE TITLE
gallery width does not stretch

### ISSUE THREAD

**Issue by ghost** [center-key/paradise#1]
it appears that the deployed site does not stretch the width of the page nor center. either width-stretching or centering the gallery would immensely improve aesthetics, and would provide improved display across different devices (especially ones with widescreen displays). this can be done with the '''.center''' attribute of an element in CSS. (apologies if this is not relevant; haven't dug deeply into the code)

(it of course should go without saying that i would love to use ppages in production as i love its clean and simple design.)

**Comment by pilafmon** [comment]
I've made significant updates to the PPAGES code in that last couple weeks.  That may have fixed the centering problem you encountered or I may not be testing with the browser you're using.

To help me reproduce the problem, what browser are you using?

**Comment by pilafmon** [comment]
The project has been rewritten from the ground up and renamed to **Paradise PHP Photo Gallery**.

The centering has been fixed and tested in Safari, Chrome, Firefox, and IE.

Example:
http://frazierart.com

The centering also looks to work correctly on the new SEO friendly single image pages:
http://frazierart.com/image/007/green-hills
