### ISSUE TITLE
Add support for running on a Microsoft Windows server

### ISSUE THREAD

**Issue by pilafmon** [center-key/paradise#15]
To address issue #14, add support for Microsoft Windows on the server-side.

This probably requires converting regular path slashes to Windows backwards `\` characters:
https://stackoverflow.com/a/43582590

```php
function normalize(path) {
   return str_replace("/", DIRECTORY_SEPARATOR, path);
   }
```

**Comment by pilafmon** [comment]
Might be something else besides the `/`:
https://stackoverflow.com/questions/4178263/make-a-path-work-both-on-linux-and-windows

**Comment by FernandoTBarros** [comment]
Man, you should REALLY make explicit that is not Windows compatible!
I've lost all my day trying to make it work on Windows with IIS but I gave up.
Only changing this directory separator is not enough.

**Comment by pilafmon** [comment]
Man, you should REALLY make explicit that you did not follow the instructions!
Changing this directory separator is not even required.

**Comment by pilafmon** [comment]
If you encountered a specific problem, please post the details here and we'll try to get it resolved.

**Comment by FernandoTBarros** [comment]
Nevermind. I told you I gave up.
But you should try to run in a Windows once to see a lot of troubles you will got.

**Comment by pilafmon** [comment]
I suspect the troubles were related to file permissions not specific to Windows.  If you run your own server and skip the FTP install step, you must manually set the appropriate write permissions.  FTP for web hosting service providers is generally configured to set permissions correctly.
