### ISSUE TITLE
Messages nit received

### ISSUE THREAD

**Issue by jansenlm** [center-key/paradise#19]
Hi, the messages sent on the contact page are send according the message on the screen but are not received. The email address of the administrator is correctly filled on the console page. Someone a suggestion? Regards Bert LMP Jansen

**Comment by pilafmon** [comment]
It's possible your PHP server is not configured to send email.  Can you verify if the `mail()` function is supported on your server?  There's a simple script you can use to test your server at: http://centerkey.com/php/

Note to self: Paradise should probably be enhanced to check if mail is enabled before attempting to send mail.  See: http://tutorialspage.com/php-check-if-mail-function-is-enabled-on-your-server/

**Comment by jansenlm** [comment]
Thanks for the info and references. Problem solved! Thanks again Regards Bert LMP Jansen
