### ISSUE TITLE
Uploaded photo is flipping 180 degrees

### ISSUE THREAD

**Issue by gleonard1236** [center-key/paradise#24]
When I upload a new image to my gallery the image flips 180 degrees and then appears upside down in my gallery.
Can you tell me something?
Thank you,
George

**Comment by pilafmon** [comment]
The original uploaded image is resized to create both the thumbnail and the final image for the gallery viewer.  I've never seen this "upside down" bug before, so maybe it's related to a bug in the resize library that only affects certain images.

Is your gallery public facing?  If I can see an example of the bug, I might be able to pinpoint the problem and create a fix.

**Comment by gleonard1236** [comment]
Thank for your reply.  I have discovered, after some deeper searching, that the problem I stated below is not a problem with the paradise software.  It has to do with old photo's rotation information that was somehow stored at times incorrectly.  This information is showing up in newer technologies affecting how images are positioned.  This is not your problem.  Thanks just the same for your interest and you can forget my below request.
Best wishes,
George
From : ***@***.***
Date : 07/02/2023 - 22:59 (CEST)
To : ***@***.***
Cc : ***@***.***, ***@***.***
Subject : Re: [center-key/paradise] Uploaded photo is flipping 180 degrees (Issue #24)
The original uploaded image is resized to create both the thumbnail and the final image for the gallery viewer. I've never seen this "upside down" bug before, so maybe it's related to a bug in the resize library that only affects certain images.
Is your gallery public facing? If I can see an example of the bug, I might be able to pinpoint the problem and create a fix.
