### ISSUE TITLE
I cannot get into my newly downloaded console

### ISSUE THREAD

**Issue by gleonard1236** [center-key/paradise#25]
Hello center-key/paradise,

I have just restarted my paradise gallery by canceling my previous one and re-downloading a new gallery from the paradise console.  However, whenever I try to get into the console of the new gallery with http://localhost/gallery/console I continually get the following error: 

Warning: file_put_contents(C:\xampp\htdocs\gallery\console\admin-server/../../~data~/login-message.html): failed to open stream: No such file or directory in C:\xampp\htdocs\gallery\console\admin-server\library.php on line 55
Error initializing file, check permissions for: C:\xampp\htdocs\gallery\console\admin-server/../../~data~/login-message.html

I have been running paradise on my local PC previously with an apache server and have never had any problems.

Can you please help me?

Thank you,
George

**Comment by pilafmon** [comment]
The new **v0.6.3** release has a more robust way to initialize folders.

I don't know for sure if the new version will fix the problem you're encountering, but the error message has been updated to show a cleaner normalized filename that will be more helpful for debugging.

**Comment by gleonard1236** [comment]
Hello Paradise, 
Thank you for your email below.  I would like you to know that all issues that I have previously had have been resolved.  Thus Paradise is going beautifully for me.  Great piece of software.
Thank you,
George
----Original Message----
From : ***@***.***
Date : 13/02/2023 - 13:12 (CEST)
To : ***@***.***
Cc : ***@***.***, ***@***.***
Subject : Re: [center-key/paradise] I cannot get into my newly downloaded console (Issue #25)
The new v0.6.3 release has a more robust way to initialize folders.
I don't know for sure if the new version will fix the problem you're encountering, but the error message has been updated to show a cleaner normalized filename that will be more helpful for debugging.
