### ISSUE TITLE
Upload failed

### ISSUE THREAD

**Issue by phengstman** [center-key/paradise#8]
It's looking great, But I can't upload any photos (message “Upload failed” received). I've tried changing permissions but no success. Any ideas where to look? 
I’m running on Apache 2.2 and php 5.3.29

**Comment by pilafmon** [comment]
The problem likely is related to file permissions.  The new release (v0.1.7) has debug mode enabled for file uploads.  Try the new version and open your browser's JS console.  You should see a status message when attempting to upload files.

Releases:
[github.com/center-key/paradise/tree/master/releases](https://github.com/center-key/paradise/tree/master/releases)

**Comment by phengstman** [comment]
Sorry, for the late response. Work was demanding hard. It's not a permission issue. I got a 501 response. Looks like e a sercurity mod setting of the webserver. I can't change that setting.

**Comment by pilafmon** [comment]
This problem could be hard to debug remotely, but please attach:
1) Screenshot of error and/or URL (if you don't want to disclose the domain, just the URL path is fine)
2) Output from JavaScript console: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers
