### ISSUE TITLE
admin email address and password not saved

### ISSUE THREAD

**Issue by jansenlm** [center-key/paradise#9]
It after installation entered email address and password is not saved, eliminating the program starts. Anyone have a suggestion on what settings need to be adjusted? MVG Bert

**Comment by jansenlm** [comment]
Error initializing file

**Comment by pilafmon** [comment]
The user authentication data is stored on your server in a folder named `secure-{CODE}` where `{CODE}` is a long number used to hide the folder for security reasons.

Example folder name:

```
gallery/~data~/secure-347179886533298346471351541
```

If you delete the `secure-{CODE}` folder, Paradise will automatically regenerate the folder so you can re-enter your login credentials.

After the folder is deleted, visit:<br>http://example.com/gallery/console

Replace `example.com` in the above link with your actual domain name.

**Comment by pilafmon** [comment]
New FAQ created:
https://github.com/center-key/paradise/wiki/FAQ#5-how-do-i-reset-my-password
